INSERT INTO RESTAURANT(ID,RESTAURANT_NAME,RESTAURANT_LOCATION,ZIP_CODE) VALUES (1,'Hebs Kosova',35);
INSERT INTO RESTAURANT(ID,RESTAURANT_NAME,RESTAURANT_LOCATION,ZIP_CODE) VALUES (2,'KFC Kosova',20);
INSERT INTO USERS(ID,USERNAME,CITY,STATE,ZIP_CODE) VALUES (1,'andimashkulli','Prizren','Kosovo',12);
INSERT INTO USERS(ID,USERNAME,CITY,STATE,ZIP_CODE) VALUES (2,'arbershala','Peje','Kosovo',13);
INSERT INTO USERS(ID,USERNAME,CITY,STATE,ZIP_CODE) VALUES (3,'adembytyqi','Gjakove','Kosovo',14);
INSERT INTO DINING_REVIEW(ID,REVIEWER_NAME,RESTAURANT_ID,RATE,COMMENT,REVIEW_STATUS) VALUES (1,'adembytyqi',3,5,'Good food','PENDING');
INSERT INTO DINING_REVIEW(ID,REVIEWER_NAME,RESTAURANT_ID,RATE,COMMENT,REVIEW_STATUS) VALUES (2,'andimashkulli',1,5,'Amazing','PENDING');
INSERT INTO DINING_REVIEW(ID,REVIEWER_NAME,RESTAURANT_ID,RATE,COMMENT,REVIEW_STATUS) VALUES (3,'arbershala',2,4,'Nice','PENDING');

